spring:
  cloud:
    gateway:
      routes:
        - id: MLModelTrainigService
          uri: http://MLMODELTRAINIGSERVICE
          predicates:
            - Path=/**
          filters:
            - name: AuthenticationFilter